version: "3"

services:
  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: michael.cu@iainnovations.com
    networks:
      - backend
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

  express:
    depends_on:
      - frontend
    build:
      context: express
      args:
        - dir=/opt/example.com/
        - port=3000
        - env=dev
    image: express-server
    container_name: express-server-container
    volumes:
      - ./express/src:/opt/example.com/src
      - ./express/dist:/opt/example.com/dist
    networks:
      - backend

volumes:
  letsencrypt:
  express:

networks:
  backend:
    driver: "bridge"
